### ISSUE TITLE
It doesn't generate the video, help :(

### ISSUE THREAD

**Issue by Durahm** [Doubiiu/ToonCrafter#61]
Why does this happen? It happens when I click to generate the video from the example image that is on the page. I spent hours trying to understand, I am not a programmer and it frustrates me :(
Python 3.11.9
print(torch.__version__)
2.5.1+cu118
print(gradio.__version__)
5.4.0

![imagen_2024-11-01_001713997](https://github.com/user-attachments/assets/78d70018-23c7-446f-967a-419df0cad23c)

C:\ToonCrafter-main\scripts\gradio\i2v_test_application.py:59: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.no_grad(), torch.cuda.amp.autocast():
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\scripts\gradio\i2v_test_application.py", line 60, in get_image
    text_emb = model.get_learned_conditioning([prompt])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\lvdm\models\ddpm3d.py", line 602, in get_learned_conditioning
    c = self.cond_stage_model.encode(c)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\lvdm\modules\encoders\condition.py", line 234, in encode
    return self(text)
           ^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\lvdm\modules\encoders\condition.py", line 211, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\lvdm\modules\encoders\condition.py", line 218, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ToonCrafter-main\lvdm\modules\encoders\condition.py", line 230, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\transformer.py", line 250, in attention
    return self.attn(
           ^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\functional.py", line 6131, in multi_head_attention_forward
    raise RuntimeError(
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

**Comment by Doubiiu** [comment]
Could you confirm that you have installed the correct version of the packages? for example open-clip?

**Comment by 7R4C341** [comment]
Detailed Summary of the Dimension Issue in attn_mask in ToonCrafter

The error occurs due to a mismatch in the dimensions of the attention mask (attn_mask) used during the execution of the transformer in the model. This issue specifically arises when attn_mask does not meet the expected dimensions required by PyTorch's multi_head_attention_forward function.
Identified Causes

    Incompatible Dimensions of attn_mask:
        The transformer expects the attention mask to have either a 2D shape ([n_ctx, n_ctx]) or a 3D shape ([batch_size, n_ctx, n_ctx]).
        Currently, attn_mask is generated with an incompatible 4D shape ([1, 77, 77, 1]), which causes an error when passed to the transformer.

    Improper Generation of attn_mask:
        The issue likely stems from how self.model.attn_mask is defined and expanded.
        It is possible that attn_mask is being processed incorrectly before being used in text_transformer_forward.

    Compatibility with PyTorch and Transformers:
        Recent changes in PyTorch and its transformer functionality might have altered the input requirements for multi_head_attention_forward, causing previously valid implementations to fail.

    Unnecessary Additional Processing:
        Some operations applied to attn_mask (such as unsqueeze and expand) have introduced extra, unnecessary dimensions, leading to conflicts.

Error Manifestation

The error appears with the following message:

RuntimeError: The shape of the 3D attn_mask is torch.Size([1, 77, 77]), but should be (batch_size, 1, 1).

This indicates that the current mask ([1, 77, 77]) does not meet the transformer's expectations, which require a mask of the form (batch_size, 1, 1) or a similar shape.

**Comment by 7R4C341** [comment]
better use this repository and follow the steps: https://github.com/sdbds/ToonCrafter-for-windows 

if you have problems with line 221, replace this function: 

"def save_videos(batch_tensors, savedir, filenames, fps=10)"

with this one below:
C:\ToonCrafter-for-windows\scripts\evaluation\funcs.py

```python
def save_videos(batch_tensors, savedir, filenames, fps=10):
    # b,samples,c,t,h,w
    n_samples = batch_tensors.shape[1]
    for idx, vid_tensor in enumerate(batch_tensors):
        video = vid_tensor.detach().cpu()
        video = torch.clamp(video.float(), -1., 1.)
        video = video.permute(2, 0, 1, 3, 4)  # t,n,c,h,w
        frame_grids = [torchvision.utils.make_grid(framesheet, nrow=int(n_samples)) for framesheet in video]  # [3, 1*h, n*w]
        grid = torch.stack(frame_grids, dim=0)  # stack in temporal dim [t, 3, n*h, w]
        grid = (grid + 1.0) / 2.0
        grid = (grid * 255).to(torch.uint8).permute(0, 2, 3, 1).numpy()
        height, width, _ = grid[0].shape
        savepath = os.path.join(savedir, f"{filenames[idx]}.mp4")
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Usa 'mp4v' o 'XVID'
        out = cv2.VideoWriter(savepath, fourcc, fps, (width, height))
        for frame in grid:
            frame_bgr = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)  # Convertir a BGR para OpenCV
            out.write(frame_bgr)
        out.release()
```
